### ISSUE TITLE
Relationship to the built-in BTRFS storage driver?

### ISSUE THREAD

**Issue by NKnusperer** [anybox/buttervolume#48]
Hello, what is the relationship between `buttervolume` and [the built-in BTRFS storage driver](https://docs.docker.com/storage/storagedriver/btrfs-driver/) ?
I'm a bit confused because in the [Running the plugin](https://github.com/anybox/buttervolume#id9) section `--volume-driver=anybox/buttervolume:latest` is used while in [Creating and deleting volumes](https://github.com/anybox/buttervolume#id11) it is  `volume-driver=btrfs`.
Thanks in advance for the clarification :)

**Comment by NKnusperer** [comment]
Thank you.
Should we use the built-in btrfs storage driver in conjunction with Buttervolume?

**Comment by ccomb** [comment]
You can use any storage driver with buttervolume since it's unrelated.
I personnaly use it both on my 100% BTRFS laptop with a btrfs storage driver, and on a Flatcar server whose storage driver is overlay2 on top of an ext4 partition, with just a BTRFS parttion for buttervolume.

(BTW I've fixed the doc, thanks again)

**Comment by ccomb** [comment]
Just a remark the `btrfs` name must still be used when the package is used manually with `buttervolume run` without building the docker driver.
